    The output of this corrected code will be:

  Exception in thread "main" ExceptionDemo3
	at FinallyDemo.testFinally(FinallyDemo.java:13)
	at FinallyDemo.main(FinallyDemo.java:5)
