Exception in thread "main" ExceptionDemo3
    at FinallyDemo.testFinally(FinallyDemo.java:15)
    at FinallyDemo.main(FinallyDemo.java:6)
